import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { resolveCapability } from './capi-client.mjs';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const team = process.env.VEKLOM_DEPARTMENT;
const missionPath = process.env.VEKLOM_MISSION_PATH;
const outputPath = process.env.VEKLOM_REPORT_PATH;
const key = process.env.VEKLOM_AGENT_API_KEY || process.env.OPENAI_API_KEY;
const model = process.env.VEKLOM_AGENT_MODEL;
const baseUrl = (process.env.VEKLOM_AGENT_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
if (!team || !missionPath || !outputPath || !key || !model) throw new Error('department worker missing required environment');
async function read(path) { return readFile(path, 'utf8'); }
const mission = JSON.parse(await read(missionPath));
const teamDoc = await read(join(ROOT,'teams',team,'team.md'));
const roster = await read(join(ROOT,'teams',team,'agents','roster.md'));
const capability = await resolveCapability('department-alignment', {department:team, mission_id:mission.mission_id, production_mutation:false});
const prompt = `You are child worker ${team}, spawned by the Veklom Command Desk parent agent.\n\nMission: ${JSON.stringify(mission)}\n\nTeam doctrine:\n${teamDoc}\n\nRoster:\n${roster}\n\ncAPI capability admission:\n${JSON.stringify(capability)}\n\nReturn JSON only with mission_id, department, captain, mission_understanding, owned_systems, risks, forbidden_actions, definition_of_done, handoff_to, status. status must be aligned, blocked, or needs_clarification. If anything is ambiguous, use needs_clarification and state the question. Do not claim live production, deployment, secret rotation, or evidence persistence. Do not call tools directly; cAPI is the only capability boundary.`;
const response = await fetch(`${baseUrl}/chat/completions`, {method:'POST', headers:{'content-type':'application/json','authorization':`Bearer ${key}`}, body:JSON.stringify({model,temperature:0.1,messages:[{role:'system',content:'You are a governed Veklom department worker. Return valid JSON only.'},{role:'user',content:prompt}]})});
const payload = await response.json();
if (!response.ok) throw new Error(`model request failed (${response.status})`);
const content = payload.choices?.[0]?.message?.content;
const fenced = content?.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1] || content;
const report = JSON.parse(fenced.trim());
const required = ['mission_id','department','captain','mission_understanding','owned_systems','risks','forbidden_actions','definition_of_done','handoff_to','status'];
for (const field of required) if (!(field in report)) throw new Error(`${team}: missing ${field}`);
if (report.mission_id !== mission.mission_id || report.department !== team) throw new Error(`${team}: identity mismatch`);
if (!['aligned','blocked','needs_clarification'].includes(report.status)) throw new Error(`${team}: invalid status`);
report.worker_id = randomUUID(); report.parent = 'command-desk'; report.capi_admission = capability; report.reported_at = new Date().toISOString();
await writeFile(outputPath, JSON.stringify(report)+'\n');
console.log(JSON.stringify({team,status:report.status,worker_id:report.worker_id}));
